Repository WorldBoxOpenMods/ModLoader, pull requests merged in 2024-08, with the labels that each got.

#20 add IsWorkshopLoaded info to ModDeclare and extension method for getting ModDeclare based on Assembly
  api/ModDeclare.cs
  resources/commit
Labels: enhancement

#23 Bugfix: Move code from constructor to OnLoad
  api/BasicMod.cs
Labels: bug

#22 add feature manager and according interfaces alongside BasicMod<T> implementation
  api/BasicMod.cs
  api/IFeatureLoadManaged.cs
  api/IModFeature.cs
  api/IModFeatureManager.cs
  api/ModFeature.cs
  api/ModFeatureManager.cs
  resources/commit
Labels: documentation, enhancement

#24 add more feature types
  api/FeatureLoadException.cs
  api/IModFeature.cs
  api/ModFeature.cs
  api/ModFeatureManager.cs
  api/ModFeatureRequirementList.cs
  api/features/ModAssetFeature.cs
  api/features/ModButtonFeature.cs
  api/features/ModGodPowerButtonFeature.cs
  api/features/ModObjectFeature.cs
  api/features/ModPowerTabFeature.cs
  api/features/ModWindowButtonFeature.cs
Labels: documentation, enhancement
